name: build

on:
  push:
    branches: [ master, dev ]
    paths:
      - 'Source/**/*.cs'
      - 'Source/**/*.csproj'
  pull_request:
    paths:
      - '**/*.cs'
      - '**/*.csproj'
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    uses: KSPModdingLibs/KSPBuildTools/.github/workflows/build.yml@main
